version: '3.9'

services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - "5454:5432"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres