CREATE TABLE public.checkin (
  id UUID PRIMARY KEY,
  user_id INTEGER NOT NULL,
  timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL
);